name: build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build gcc  # Add necessary compilers/tools

      - name: Configure Meson build
        run: meson setup builddir

      - name: Compile the project
        run: meson compile -C builddir

      - name: Run tests
        run: meson test -C builddir --print-errorlogs
